Adding libcxxabi test config
Without this file when compiling with the following flags: `cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;cross-project-tests;flang;libc;libclc;lld;lldb;openmp;polly' -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;compiler-rt;libunwind' -DLLVM_BUILD_DOCS=OFF -DLLVM_ENABLE_BINDINGS=OFF -DLIBCXX_CXX_ABI=libcxxabi`

The following error appears:

#60770 

However it's to be noted that even with this file added and running `ninja check-all` on the build folder the following error appears:

```cpp
[28/29] Running all regression tests
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/arshia/Desktop/llvm-project/build/bin/clang
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld.lld: /home/arshia/Desktop/llvm-project/build/bin/ld.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using lld-link: /home/arshia/Desktop/llvm-project/build/bin/lld-link
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld64.lld: /home/arshia/Desktop/llvm-project/build/bin/ld64.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using wasm-ld: /home/arshia/Desktop/llvm-project/build/bin/wasm-ld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using lldb: /home/arshia/Desktop/llvm-project/build/bin/lldb
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang++: /home/arshia/Desktop/llvm-project/build/bin/clang++
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang-cl: /home/arshia/Desktop/llvm-project/build/bin/clang-cl
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/arshia/Desktop/llvm-project/build/bin/clang
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/arshia/Desktop/llvm-project/build/bin/clang
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/arshia/Desktop/llvm-project/build/bin/clang
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/arshia/Desktop/llvm-project/build/bin/clang
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld.lld: /home/arshia/Desktop/llvm-project/build/bin/ld.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using lld-link: /home/arshia/Desktop/llvm-project/build/bin/lld-link
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld64.lld: /home/arshia/Desktop/llvm-project/build/bin/ld64.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using wasm-ld: /home/arshia/Desktop/llvm-project/build/bin/wasm-ld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld.lld: /home/arshia/Desktop/llvm-project/build/bin/ld.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using lld-link: /home/arshia/Desktop/llvm-project/build/bin/lld-link
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld64.lld: /home/arshia/Desktop/llvm-project/build/bin/ld64.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using wasm-ld: /home/arshia/Desktop/llvm-project/build/bin/wasm-ld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using clang: /home/arshia/Desktop/llvm-project/build/bin/clang
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld.lld: /home/arshia/Desktop/llvm-project/build/bin/ld.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using lld-link: /home/arshia/Desktop/llvm-project/build/bin/lld-link
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using ld64.lld: /home/arshia/Desktop/llvm-project/build/bin/ld64.lld
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/llvm/config.py:459: note: using wasm-ld: /home/arshia/Desktop/llvm-project/build/bin/wasm-ld
llvm-lit: /home/arshia/Desktop/llvm-project/libcxx/utils/libcxx/test/newconfig.py:19: note: (llvm-libunwind-shared.cfg.in) Using %{cxx} substitution: '/home/arshia/Desktop/llvm-project/build/./bin/clang++'
llvm-lit: /home/arshia/Desktop/llvm-project/libcxx/utils/libcxx/test/newconfig.py:19: note: (llvm-libunwind-shared.cfg.in) Using %{flags} substitution: ' --target=x86_64-unknown-linux-gnu'
llvm-lit: /home/arshia/Desktop/llvm-project/libcxx/utils/libcxx/test/newconfig.py:19: note: (llvm-libunwind-shared.cfg.in) Using %{compile_flags} substitution: '-nostdinc++ -I %{include} -funwind-tables -std=c++2b -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-c++11-extensions -Wno-noexcept-type -Wno-atomic-alignment -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_DISABLE_AVAILABILITY -Werror=thread-safety -Wuser-defined-warnings'
llvm-lit: /home/arshia/Desktop/llvm-project/libcxx/utils/libcxx/test/newconfig.py:19: note: (llvm-libunwind-shared.cfg.in) Using %{link_flags} substitution: '-L %{lib} -Wl,-rpath,%{lib} -lunwind -ldl -Wl,--export-dynamic'
llvm-lit: /home/arshia/Desktop/llvm-project/libcxx/utils/libcxx/test/newconfig.py:19: note: (llvm-libunwind-shared.cfg.in) Using %{exec} substitution: '%{executor} --execdir %T -- '
llvm-lit: /home/arshia/Desktop/llvm-project/libcxx/utils/libcxx/test/newconfig.py:19: note: (llvm-libunwind-shared.cfg.in) All available features: fdelayed-template-parsing, buildhost=linux, stdlib=libc++, has-fblocks, verify-support, c++2b, clang-17.0, thread-safety, has-unix-headers, -faligned-allocation, objective-c++, diagnose-if-support, libcpp-has-no-incomplete-format, clang-17, locale.en_US.UTF-8, has-fconstexpr-steps, long_tests, clang, target=x86_64-unknown-linux-gnu, linux, clang-17.0.0, glibc-old-ru_RU-decimal-point, -fsized-deallocation, host-has-gdb-with-python, stdlib=llvm-libc++
llvm-lit: /home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/TestingConfig.py:141: fatal: unable to parse config file '/home/arshia/Desktop/llvm-project/build/runtimes/runtimes-bins/libcxxabi/test/lit.site.cfg', traceback: Traceback (most recent call last):
  File "/home/arshia/Desktop/llvm-project/llvm/utils/lit/lit/TestingConfig.py", line 130, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/home/arshia/Desktop/llvm-project/build/runtimes/runtimes-bins/libcxxabi/test/lit.site.cfg", line 11
    config.user_mode_emulation = 
                                 ^
SyntaxError: invalid syntax

FAILED: CMakeFiles/check-all /home/arshia/Desktop/llvm-project/build/CMakeFiles/check-all 
cd /home/arshia/Desktop/llvm-project/build && /usr/bin/python3.10 /home/arshia/Desktop/llvm-project/build/./bin/llvm-lit -sv --param USE_Z3_SOLVER=0 --param flang_site_config=/home/arshia/Desktop/llvm-project/build/tools/flang/test/lit.site.cfg.py --param polly_site_config=/home/arshia/Desktop/llvm-project/build/tools/polly/test/lit.site.cfg --param polly_unit_site_config=/home/arshia/Desktop/llvm-project/build/tools/polly/test/Unit/lit.site.cfg /home/arshia/Desktop/llvm-project/build/projects/openmp/runtime/test /home/arshia/Desktop/llvm-project/build/projects/openmp/libomptarget/test/nvptx64-nvidia-cuda /home/arshia/Desktop/llvm-project/build/projects/openmp/libomptarget/test/nvptx64-nvidia-cuda-LTO /home/arshia/Desktop/llvm-project/build/projects/openmp/libomptarget/test/x86_64-pc-linux-gnu /home/arshia/Desktop/llvm-project/build/projects/openmp/libomptarget/test/x86_64-pc-linux-gnu-LTO /home/arshia/Desktop/llvm-project/build/projects/openmp/tools/archer/tests /home/arshia/Desktop/llvm-project/build/projects/openmp/tools/multiplex/tests /home/arshia/Desktop/llvm-project/build/projects/openmp/libompd/test /home/arshia/Desktop/llvm-project/build/projects/cross-project-tests /home/arshia/Desktop/llvm-project/build/tools/clang/tools/extra/include-cleaner/test /home/arshia/Desktop/llvm-project/build/tools/clang/tools/extra/pseudo/test /home/arshia/Desktop/llvm-project/build/tools/clang/tools/extra/clangd/test/../unittests /home/arshia/Desktop/llvm-project/build/tools/clang/tools/extra/clangd/test /home/arshia/Desktop/llvm-project/build/tools/clang/tools/extra/test /home/arshia/Desktop/llvm-project/build/tools/clang/test /home/arshia/Desktop/llvm-project/build/tools/lld/test /home/arshia/Desktop/llvm-project/build/tools/lldb/test /home/arshia/Desktop/llvm-project/build/tools/mlir/test /home/arshia/Desktop/llvm-project/build/tools/flang/test /home/arshia/Desktop/llvm-project/build/tools/polly/test @/home/arshia/Desktop/llvm-project/build/runtimes/runtimes-bins/lit.tests /home/arshia/Desktop/llvm-project/build/utils/lit /home/arshia/Desktop/llvm-project/build/test
ninja: build stopped: subcommand failed.
```